## Since calculation of inverses of matrices is usually a time-consuming computation,
## make use of caching is a good practice.

## makeCacheMatrix <- function (x = matrix())
## Provides a structure of getters and setters of a variable.
## Returns list with columns "set", "get", "setinverse" and "getinverse".

makeCacheMatrix <- function(x = matrix()) {
        m <- NULL
        set <- function(y) {
                x <<- y
                m <<- NULL
        }
        get <- function() x
        setinverse <- function(solve) m <<- solve
        getinverse <- function() m
        list(set = set, get = get,
                 setinverse = setinverse,
                 getinverse = getinverse)
}


## cacheSolve <- function (x, ...)
## x must be an invertible matrix.
## Making use of structure generated by makeCacheMatrix,
## caches results from a inverse matrix calculation.
## Returns a matrix, inverse of x.

cacheSolve <- function(x, ...) {
        m <- x$getinverse()
        if(!is.null(m)) {
                message("getting cached data")
                return(m)
        }
        data <- x$get()
        m <- solve(data, ...)
        x$setinverse(m)
        m
}
